src/Administration/Entity/User.php
<?php

namespace App\Administration\Entity;

use App\Shop\Entity\Invoice;
use App\Shop\Entity\Ordering;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Administration\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="json")
     */
    protected $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    protected $password;

    /**
     * @var $plainPassword
     */
    protected $plainPassword;

    /**
     * @var $gender
     * @ORM\Column(type="string")
     */
    protected $gender;

    /**
     * @var $last_name
     * @ORM\Column(type="string")
     */
    protected $last_name;

    /**
     * @var $first_name
     * @ORM\Column(type="string")
     */
    protected $first_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Shop\Entity\Ordering", mappedBy="user", cascade={"persist"})
     */
    protected $orderings;

    /**
     * @ORM\ManyToMany(targetEntity="App\Administration\Entity\UserAddress", cascade={"persist"})
     * @ORM\JoinTable(name="users_addresses",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="user_address_id", referencedColumnName="id")})
     */
    private $addresses;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->addresses = new ArrayCollection();
        $this->orderings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function addRole(string $role)
    {
        if (!in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
            return true;
        } else {
            return false;
        }
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string
     */
    public function getGender(): ?string
    {
        return $this->gender;
    }

    /**
     * @param string $gender
     */
    public function setGender($gender): void
    {
        $this->gender = $gender;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param mixed $last_name
     */
    public function setLastName($last_name): void
    {
        $this->last_name = $last_name;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * @param mixed $first_name
     */
    public function setFirstName($first_name): void
    {
        $this->first_name = $first_name;
    }

    /**
     * @return mixed
     */
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * @param mixed $plainPassword
     */
    public function setPlainPassword($plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * @return Collection
     */
    public function getOrderings(): Collection
    {
        return $this->orderings;
    }

    /**
     * @param Ordering $ordering
     * @return void
     */
    public function addOrdering(Ordering $ordering): void
    {
        if (!$this->orderings->contains($ordering)) {
            $this->orderings->add($ordering);
            $ordering->setUser($this);
        }
    }

    /**
     * @return Collection
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    /**
     * @param UserAddress $address
     * @return User|boolean
     */
    public function addAddress(UserAddress $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses->add($address);
            return $this;
        } else {
            return false;
        }
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function serialize()
    {
        return serialize([
            $this->id,
            $this->email,
            $this->password,
            $this->roles,
            $this->gender
        ]);
    }

    public function unserialize($serialized): void
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            $this->roles,
            $this->gender
            ) = unserialize($serialized, [__CLASS__]);
    }

    public function __toString(): string
    {
        return $this->email;
    }
}

src/Administration/Entity/UserAddress.php
<?php
/**
 * Created by PhpStorm.
 * User: seymos
 * Date: 26/02/19
 * Time: 18:22
 */

namespace App\Administration\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Administration\Repository\UserAddressRepository")
 * @ORM\Table(name="user_address")
 */
class UserAddress
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $type;

    /**
     * @ORM\Column(type="string")
     */
    private $number;

    /**
     * @ORM\Column(type="string")
     */
    private $street;

    /**
     * @ORM\Column(type="string")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string")
     */
    private $city;

    /**
     * @ORM\Column(type="string")
     */
    private $country;

    /**
     * @ORM\OneToMany(targetEntity="App\Shop\Entity\Ordering", mappedBy="user_address", cascade={"persist"})
     */
    private $orderings;

    public function __construct()
    {
        $this->orderings = new ArrayCollection();
    }

    /**
     * @return integer
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * @return string
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * @param string $number
     */
    public function setNumber(string $number): void
    {
        $this->number = $number;
    }

    /**
     * @return string
     */
    public function getStreet(): ?string
    {
        return $this->street;
    }

    /**
     * @param string $street
     */
    public function setStreet(string $street): void
    {
        $this->street = $street;
    }

    /**
     * @return string
     */
    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    /**
     * @param string $zip_code
     */
    public function setZipCode(string $zip_code): void
    {
        $this->zip_code = $zip_code;
    }

    /**
     * @return string
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity(string $city): void
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry(string $country): void
    {
        $this->country = $country;
    }
}

src/Shop/Entity/BaseOrder.php
<?php
/**
 * Created by PhpStorm.
 * User: seymos
 * Date: 26/02/19
 * Time: 17:29
 */

namespace App\Shop\Entity;

use Doctrine\ORM\Mapping as ORM;

abstract class BaseOrder
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $reference;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date_creation;

    /**
     * @ORM\Column(type="string")
     */
    protected $status;

    /**
     * @ORM\Column(type="float")
     */
    protected $total_ht;

    /**
     * @ORM\Column(type="float")
     */
    protected $total_vat;

    /**
     * @ORM\Column(type="float")
     */
    protected $total_ttc;

    public function __construct()
    {
        $this->date_creation = new \DateTime('now');
    }

    /**
     * @param integer $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @return mixed
     */
    public function getDateCreation()
    {
        return $this->date_creation;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @return mixed
     */
    public function getTotalHt()
    {
        return $this->total_ht;
    }

    /**
     * @return mixed
     */
    public function getTotalVat()
    {
        return $this->total_vat;
    }

    /**
     * @return mixed
     */
    public function getTotalTtc()
    {
        return $this->total_ttc;
    }
}

src/Shop/Form/ProductType.php
<?php

namespace App\Administration\Form;

use App\Administration\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('price')
            ->add('reference')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Shop/Controller/FunnelController.php
<?php
/**
 * Created by PhpStorm.
 * User: seymos
 * Date: 23/02/19
 * Time: 18:44
 */

namespace App\Shop\Controller;


use App\Shop\Entity\Color;
use App\Shop\Entity\Patch;
use App\Shop\Entity\Shape;
use App\Shop\Entity\Size;
use App\Shop\Repository\ColorRepository;
use App\Shop\Repository\PatchRepository;
use App\Shop\Repository\ShapeRepository;
use App\Shop\Services\CartService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class FunnelController
 * @package App\Shop\Controller
 * @Route(path="/configuration")
 */
class FunnelController extends AbstractController
{
    private $shapeRepository;
    private $colorRepository;
    private $patchRepository;

    public function __construct(ShapeRepository $shapeRepository, ColorRepository $colorRepository, PatchRepository $patchRepository)
    {
        $this->shapeRepository = $shapeRepository;
        $this->colorRepository = $colorRepository;
        $this->patchRepository = $patchRepository;
    }

    /**
     * @Route(path="/forme", name="select_shape")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function shape(Request $request, SessionInterface $session): Response
    {
        if ($request->isMethod('POST') && null !== $request->request->get('shape_id')) {
            /** @var Shape $shape */
            $shape = $this->getDoctrine()->getRepository(Shape::class)->find($request->request->get('shape_id'));
            if ($shape instanceof Shape) {
                $session->set('shape_id', $shape);
                $this->addFlash('success',"Forme de casquette ok");
                return $this->redirectToRoute('select_color');
            } else {
                $this->addFlash('error',"Cette forme n'est plus disponible");
                return $this->redirectToRoute('select_shape');
            }
        }
        return $this->render(
            'shop/shape.html.twig',
            [
                'shapes' => $this->getDoctrine()->getRepository(Shape::class)->findAvailable(),
                'ordering' => $session->get('ordering') ?? $session->get('ordering') ?? null
            ]
        );
    }

    /**
     * @Route(path="/couleur", name="select_color")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function color(Request $request, SessionInterface $session): Response
    {
        if (!$session->has('shape_id')) {
            $this->addFlash('warning',"Veuillez d'abord sélectionner une forme");
            return $this->redirectToRoute('select_shape');
        }
        if ($request->isMethod('POST') && null !== $request->request->get('color_id')) {
            /** @var Color $color */
            $color = $this->getDoctrine()->getRepository(Color::class)->find($request->request->get('color_id'));
            if ($color instanceof Color) {
                $session->set('color_id', $color);
                $this->addFlash('success',"Couleur de casquette ok");
                return $this->redirectToRoute('select_patch');
            } else {
                $this->addFlash('error',"Cette couleur n'est plus disponible");
                return $this->redirectToRoute('select_color');
            }
        }
        return $this->render(
            'shop/color.html.twig',
            [
                'colors' => $this->getDoctrine()->getRepository(Color::class)->findAvailable()
            ]
        );
    }

    /**
     * @Route(path="/ecusson", name="select_patch")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function patch(Request $request, SessionInterface $session, CartService $cartService): Response
    {
        if (!$session->has('color_id')) {
            $this->addFlash('warning',"Veuillez d'abord sélectionner une couleur");
            return $this->redirectToRoute('select_color');
        }
        if ($request->isMethod('POST') && $request->request->get('patch_id') !== null) {
            /** @var Patch $patch */
            $patch = $this->getDoctrine()->getRepository(Patch::class)->find($request->request->get('patch_id'));
            if ($patch instanceof Patch) {
                $session->set('patch_id', $patch);
                $this->addFlash('success',"Patch de casquette ok");
                return $this->redirectToRoute('select_size');
            } else {
                $this->addFlash('success',"Cet écusson n'est plus disponible");
                return $this->redirectToRoute('select_patch');
            }
        }
        return $this->render(
            'shop/patch.html.twig',
            [
                'patches' => $this->getDoctrine()->getRepository(Patch::class)->findAvailable()
            ]
        );
    }

    /**
     * @Route(path="/taille", name="select_size")
     * @param Request $request
     * @return Response
     */
    public function sizeAndQuantity(Request $request, SessionInterface $session, CartService $cartService): Response
    {
        if (!$session->has('patch_id')) {
            $this->addFlash('warning',"Veuillez d'abord sélectionner un écusson personnalisé");
            return $this->redirectToRoute('select_patch');
        }
        $sizes = $this->getDoctrine()->getRepository(Size::class)->findAvailable();
        if ($request->isMethod('POST')) {
            $size = $this->getDoctrine()->getRepository(Size::class)->find($request->request->get('product_size'));
            $quantity = $request->request->get('quantity');
            $ordering = $cartService->validateAndCreateOrdering($session, $size, $quantity);
            return $this->redirectToRoute('cart', ['reference' => $ordering->getReference()]);
        }
        return $this->render(
            'shop/size_and_quantity.html.twig',
            [
                'sizes' => $sizes
            ]
        );
    }

    public function cartRender()
    {
        return $this->render(
            'shop/cart_render.html.twig'
        );
    }
}

templates/shop/billing.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Adresse de facturation</h1>

    {{ form_start(form) }}
    {{ form_row(form.number) }}
    {{ form_row(form.street) }}
    {{ form_row(form.zipCode) }}
    {{ form_row(form.city) }}
    {{ form_row(form.country) }}
    <button type="submit">Valider mon adresse de facturation</button>
    {{ form_end(form) }}

    <form action="{{ path('cart_pay', {'reference': ordering.reference}) }}" method="post">
        {% for a in addresses %}
            <input type="radio" name="billing_address" value="{{ a.id }}"> {{ a.number }}, {{ a.street }} {{ a.zipCode }} {{ a.city }}, {{ a.country }}
        {% endfor %}
        <button type="submit">Valider mon adresse existante</button>
    </form>
{% endblock %}

templates/shop/cart.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Page panier</h1>

    {% if ordering is defined and ordering.products is defined and ordering.products|length > 0 %}
        {% set total = 0 %}
        {% for product in ordering.products %}
            {% set total = total + product.priceHt %}
        {% endfor %}
        {{ total }}
        <a href="{{ path('cart_clear') }}">Vider mon panier</a>
        {% set products = ordering.products %}
        <form action="{{ path('cart') }}" method="post">
            {% for key, p in products %}
                <div style="border: 5px solid red;">
                    {% if p != null %}
                        <p>{{ p.reference }}</p>
                        <p>{{ dump(p) }}</p>
                        <p>{{ dump(p.priceHt) }}</p>
                        <input type="hidden" name="product_quantity" data-reference="{{ p.reference }}" value="{{ p.quantity }}">
                        <p>Qté: {{ p.quantity }}</p>
                        <a href="{{ path('cart_remove_product', {'reference': p.reference}) }}">Supprimer l'article</a>
                    {% else %}
                        p est null
                    {% endif %}
                </div>
            {% endfor %}
            <input type="hidden" name="ordering_total_ht" value="{{ total }}">
            <br>
            {#            <input type="hidden" name="product_length" value="{{ products|length }}">#}
            {% if is_granted('ROLE_USER') %}
                <button type="submit" name="submit" value="cart_validation">Valider mon panier</button>
            {% else %}
                <a href="{{ path('cart_join') }}">Se connecter et valider mon panier</a>
            {% endif %}
        </form>
        <a href="{{ path('select_shape') }}">Ajouter un produit</a>
        <br><br><br>
    {% else %}
        Votre panier est vide
    {% endif %}

{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('shopping_cart') }}
{% endblock %}

templates/shop/cart_render.html.twig
{% if app.session.get('shape_id') %}
    {{ dump(app.session.get('shape_id')) }}
{% endif %}
{% if app.session.get('color_id') %}
    {{ dump(app.session.get('color_id')) }}
{% endif %}
{% if app.session.get('patch_id') %}
    {{ dump(app.session.get('patch_id')) }}
{% endif %}
{% if app.session.get('products') %}
    {% for p in app.session.get('products') %}
        {{ dump(p) }}
    {% endfor %}
{% endif %}
{% if app.session.get('ordering') %}
    {% for p in app.session.get('ordering') %}
        {{ dump(p) }}
    {% endfor %}
{% endif %}

templates/shop/color.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        .color {
            width: 80px;
            height: 80px;
            border-radius: 50%;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Sélection couleur</h1>

    {% for c in colors %}
        <p>{{ c.name }}</p>
        <p>{{ c.pricing }} €</p>
        <div class="color" style="background-color: {{ c.code }}"></div>
        <form action="{{ path('select_color') }}" method="post">
            <input type="hidden" value="{{ c.id }}" name="color_id">
            <button type="submit">Choisir</button>
        </form>
    {% endfor %}
{% endblock %}

templates/shop/join.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Accéder à votre espace</h1>

    <p>Inscription ou connexion</p>

    <h2>Connexion</h2>
    <form action="{{ path('app_login') }}" method="post">
        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email</label>
        <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" placeholder="Email" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

        <input type="hidden" name="_csrf_token"
               value="{{ csrf_token('authenticate') }}"
        >

        {#
            Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
            See https://symfony.com/doc/current/security/remember_me.html

            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" name="_remember_me"> Remember me
                </label>
            </div>
        #}

        <button class="btn btn-lg btn-primary" type="submit">
            Sign in
        </button>
    </form>

    <h2>Inscription</h2>
    {{ form_start(form) }}
    {{ form_row(form.gender) }}
    {{ form_row(form.firstName) }}
    {{ form_row(form.lastName) }}
    {{ form_row(form.email) }}
    {{ form_row(form.plainPassword) }}
    <button type="submit">Inscription</button>
    {{ form_end(form) }}
{% endblock %}

templates/shop/patch.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Sélection écusson</h1>

    {% for p in patches %}
        <p>{{ p.name }}</p>
        <p>{{ p.pricing }} €</p>
        <img src="{{ asset('uploads/patch/fixtures/' ~ p.image) }}" height="250" />
        <form action="{{ path('select_patch') }}" method="post">
            <input type="hidden" value="{{ p.id }}" name="patch_id">
            <button type="submit">Choisir</button>
        </form>
    {% endfor %}
{% endblock %}

templates/shop/pay.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
    <style>
        .StripeElement {
            box-sizing: border-box;

            height: 40px;

            padding: 10px 12px;

            border: 1px solid transparent;
            border-radius: 4px;
            background-color: white;

            box-shadow: 0 1px 3px 0 #e6ebf1;
            -webkit-transition: box-shadow 150ms ease;
            transition: box-shadow 150ms ease;
        }

        .StripeElement--focus {
            box-shadow: 0 1px 3px 0 #cfd7df;
        }

        .StripeElement--invalid {
            border-color: #fa755a;
        }

        .StripeElement--webkit-autofill {
            background-color: #fefde5 !important;
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Paiement</h1>

    {% if ordering is defined %}
        {{ dump(ordering) }}
    {% endif %}

    <form action="{{ path('stripe_payments_checkout') }}" method="post" id="payment-form">
        <div class="form-row">
            <label for="card-element">
                Payez par carte bancaire, Stripe ou Paypal !
            </label>
            <div id="card-element">
    <!-- A Stripe Element will be inserted here. -->
    </div>
            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
        </div>

        <button>Submit Payment</button>
    </form>

{#    <form action="{{ path('stripe_payments_checkout') }}" method="post" id="payment-form">#}
{#        <div class="form-row">#}
{#            <label for="card-element">#}
{#                Credit or debit card#}
{#            </label>#}
{#            <div id="card-element">#}
{#    <!-- A Stripe Element will be inserted here. -->#}
{#    </div>#}
{#            <!-- Used to display form errors. -->#}
{#            <div id="card-errors" role="alert"></div>#}
{#        </div>#}

{#        <button>Submit Payment</button>#}
{#    </form>#}

{% endblock %}

{% block javascripts %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        // Create a Stripe client.
        var stripe = Stripe('pk_test_qaOf5JZelJ3X5Mzovfr5J1RO');

        // Create an instance of Elements.
        var elements = stripe.elements();

        // Custom styling can be passed to options when creating an Element.
        // (Note that this demo uses a wider set of styles than the guide below.)
        var style = {
            base: {
                color: '#32325d',
                fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                fontSmoothing: 'antialiased',
                fontSize: '16px',
                '::placeholder': {
                    color: '#aab7c4'
                }
            },
            invalid: {
                color: '#fa755a',
                iconColor: '#fa755a'
            }
        };

        // Create an instance of the card Element.
        var card = elements.create('card', {style: style});

        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function(event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission.
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
            event.preventDefault();

            stripe.createToken(card).then(function(result) {
                console.log(result);
                if (result.error) {
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;
                } else {
                    stripeTokenHandler(result.token);
                }
            });
        });

        // Submit the form with the token ID.
        function stripeTokenHandler(token) {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            var amount = document.createElement('input');
            var currency = document.createElement('input');
            currency.setAttribute('type','hidden');
            currency.setAttribute('name','currency');
            currency.setAttribute('value','eur');
            amount.setAttribute('type','hidden');
            amount.setAttribute('name','amount');
            amount.setAttribute('value',{{ ordering.totalTtc }});
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripe_token');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);
            form.appendChild(amount);
            form.appendChild(currency);
            // Submit the form
            form.submit();
        }
    </script>
{% endblock %}

templates/shop/shape.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Sélection forme</h1>

    {% if app.session.get('ordering') %}
        Vous avez une commande en attente
    {% else %}
        Aucune commande pour l'instant
    {% endif %}

    {% for s in shapes %}
        <p>{{ s.name }}</p>
        <p>{{ s.pricing }} €</p>
        <img src="{{ asset('uploads/shape/fixtures/' ~ s.image) }}" height="250" />
        <form action="{{ path('select_shape') }}" method="post">
            <input type="hidden" value="{{ s.id }}" name="shape_id">
            <button type="submit">Choisir</button>
        </form>
    {% endfor %}
{% endblock %}

templates/shop/shipping.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1>Adresse de livraison</h1>

    {{ form_start(form) }}
    {{ form_row(form.number) }}
    {{ form_row(form.street) }}
    {{ form_row(form.zipCode) }}
    {{ form_row(form.city) }}
    {{ form_row(form.country) }}
    <input type="checkbox" name="billing">
    <button type="submit">Valider et sauvegarder mon adresse de livraison</button>
    {{ form_end(form) }}

    {{ dump(ordering) }}

    {% if addresses is defined and addresses|length > 0 %}
        <form action="{{ path('cart_shipping') }}" method="post">
            {% for a in addresses %}
                <input type="radio" name="shipping_address" value="{{ a.id }}"> {{ a.number }}, {{ a.street }} {{ a.zipCode }} {{ a.city }}, {{ a.country }}
            {% endfor %}
            <input type="checkbox" name="billing">
            <button type="submit">Valider mon adresse existante</button>
        </form>
    {% endif %}
{% endblock %}

templates/shop/size_and_quantity.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Sélection size</h1>

    {% if app.session.get('products') %}
        {% if app.session.get('products')|length > 0 %}
            Vous avez {{ app.session.get('products')|length }} produits dans votre panier
        {% endif %}
    {% else %}
        Aucune commande pour l'instant
    {% endif %}

    <form action="{{ path('select_size') }}" method="post">
        <input type="number" value="1" name="quantity">
        <select name="product_size" id="product_size">
            {% for s in sizes %}
                <option value="{{ s.id }}">{{ s.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Choisir</button>
    </form>
{% endblock %}